services:
  - type: web
    name: health-platform-api
    env: docker
    plan: free # Can be changed to pro or others
    region: oregon # Or your preferred region
    envVars:
      - key: DB_URL
        sync: false # Set this in Render dashboard for security
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
